/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveStrategySol from "./AaveStrategy.sol";
export type { aaveStrategySol };
import type * as compoundStrategySol from "./CompoundStrategy.sol";
export type { compoundStrategySol };
export type { NoxStrategy } from "./NoxStrategy";
export type { StrategyBase } from "./StrategyBase";
